# This workflow will install Python dependencies, generate new Dummy.json file, and commit to master
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gen Dummy

on:
  schedule:
    - cron: '31 2 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Random-Word
    - name: Update data/Dummy.json
      run: |
        python data/gen_dummy.py
        
        
    - name: Commit files
      run: |
        git add --all
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "workflow: Automated Dummy.json build" | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
